export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_USER_PROFILE_BY_ID = 'GET_USER_PROFILE_BY_ID';
export const ADVENTURE_LOADING = 'ADVENTURE_LOADING';
export const GET_ADVENTURES = 'GET_ADVENTURES';
export const GET_WISHED_ADVENTURES = 'GET_WISHED_ADVENTURES';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const GET_ADVENTURE = 'GET_ADVENTURE';
export const GET_USER_ADVENTURES= 'GET_USER_ADVENTURES';
export const ADD_ADVENTURE = 'ADD_ADVENTURE';
export const DELETE_ADVENTURE = 'DELETE_ADVENTURE';
export const GET_LATEST_ADVENTURES = 'GET_LATEST_ADVENTURES';
// Messages
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const GET_USER_MESSAGES = 'GET_USER_MESSAGES';
export const MESSAGES_LOADING = 'MESSAGES_LOADING';
export const GET_MESSAGE = 'GET_MESSAGE';

